_target_: pytorch_lightning.Trainer

accelerator: gpu

gpus: -1

min_epochs: 20
max_epochs: 200

# ckpt path
resume_from_checkpoint: null

# Other Config
default_root_dir: ${original_work_dir}/checkpoints_/${name}
