_target_: dataLoader.CTDataModule.CTDataModule
batch_size: 1
data_dir: ${original_work_dir}/data/Train_Mayo_CT.npy
vl_data_dir: ${original_work_dir}/data/Valid_Mayo_CT.npy
ts_data_dir: ${original_work_dir}/data/Test_Mayo_CT.npy
